version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: spotlight-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/spotlightplayers
    volumes:
      - ./src:/app/src
    command: >
      bash -c "npm install && npm run dev"
